{{- if .Values.policy.networking.enabled -}}
{{- $appName := include "app.name" . -}}
{{- $appChart := include "app.chart" . -}}
{{- $this := . -}}
{{- range $network := .Values.policy.networking.networks -}}
{{ $networkLabel := printf "%s.network/%s" $appName $network }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-%s" $appName $network | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ $appName }}
    chart: {{ $appChart }}
    heritage: {{ $this.Release.Service }}
    release: {{ $this.Release.Name }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ $networkLabel }}: "true"
  podSelector:
    matchLabels:
      {{ $networkLabel }}: "true"
{{- end -}}
{{- end -}}