{{- $appName := include "app.name" . -}}
{{- $appChart := include "app.chart" . -}}
{{- $this := . -}}
{{- range $volumeClaim := .Values.persistentVolumeClaims }}
{{- $volumeClaimName := tpl $volumeClaim.name $this }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with $volumeClaim.annotations }}
  annotations:
{{ tpl (toYaml .) $this | indent 4 }}
  {{- end }}
  name: {{ $volumeClaimName }}
  labels:
    app: {{ $appName }}
    chart: {{ $appChart }}
    heritage: {{ $this.Release.Service }}
    release: {{ $this.Release.Name }}
    {{- with $volumeClaim.labels }}
{{ tpl (toYaml .) $this | indent 4 }}
    {{- end }}
spec:
  {{- with $volumeClaim.spec }}
{{ tpl (toYaml .) $this | indent 2 }}
  {{- end }}
{{- end }}