{{- $appName := include "app.name" . -}}
{{- $appChart := include "app.chart" . -}}
{{- $component := "backend" -}}
{{- $componentName := printf "%s-%s" $appName $component -}}
{{- $this := . -}}
{{- if .Values.frontend.persistentVolumeClaim.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .Values.backend.persistentVolumeClaim.annotations }}
  annotations:
{{ tpl (toYaml .) $this | indent 4 }}
  {{- end }}
  name: {{ $componentName }}
  labels:
    app: {{ $appName }}
    chart: {{ $appChart }}
    heritage: {{ $this.Release.Service }}
    release: {{ $this.Release.Name }}
    {{ $appName }}.service: {{ $component }}
    component: {{ $component }}
spec:
  {{- with .Values.backend.persistentVolumeClaim.spec }}
{{ tpl (toYaml .) $this | indent 2 }}
  {{- end }}
{{- end }}
