{{- $appName := include "app.name" . -}}
{{- $appChart := include "app.chart" . -}}
{{- $component := "backend" -}}
{{- $componentName := printf "%s-%s" $appName $component -}}
{{- $this := . -}}
{{- if .Values.backend.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $componentName }}
  labels:
    app: {{ $appName }}
    chart: {{ $appChart }}
    heritage: {{ $this.Release.Service }}
    release: {{ $this.Release.Name }}
    {{ $appName }}.service: {{ $component }}
    component: {{ $component }}
type: Opaque
data:
{{- with .Values.backend.secret }}
  {{- range $k,$v := . }}
  {{ printf "%s: %s" $k ( b64enc $v ) }}
  {{- end}}
{{- end}}
{{- end}}