# Default .Values
nameOverride:
fullNameOverride:
openproject_image: openproject/community:12

cache:
  image: memcached
  replicas: 1
  restartPolicy: Always
  strategy: {}
  networks: 
    - frontend
    - backend
  env: {}
  annotations: {}
  labels: {}
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  metrics:
    enabled: true
    image: quay.io/prometheus/memcached-exporter:latest
    env: {}
    annotations: {}
    labels: {}
    livenessProbe: {}
    readinessProbe: {}
    resources: {}
  service:
    type: ClusterIP
    annotations: {}
    labels: {}

database:
  image: postgres:13
  replicas: 1
  restartPolicy: Always
  strategy:
    type: Recreate
  networks: 
    - frontend
    - backend
  env:
    POSTGRES_DB: openproject
  secret:
    POSTGRES_PASSWORD: p4ssw0rd
  annotations: {}
  labels: {}
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  terminationGracePeriodSeconds: 60
  persistentVolumeClaim:
    enabled: true
    annotations: {}
    spec:
      # storageClassName: ""
      volumeName: '{{ template "app.name" . }}-database'
  metrics:
    enabled: true
    image: prometheuscommunity/postgres-exporter:latest
    env: {}
    annotations: {}
    labels: {}
    livenessProbe: {}
    readinessProbe: {}
    resources: {}
  service:
    type: ClusterIP
    annotations: {}
    labels: {}


frontend:
  image: #if not set here, taken from global variable openproject_image
  replicas: 1
  restartPolicy: Always
  strategy: {}
  networks: 
    - frontend
  env:
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
    RAILS_CACHE_STORE: memcache
    RAILS_MAX_THREADS: "16"
    RAILS_MIN_THREADS: "4"
    OPENPROJECT_EDITION: standard
  annotations: {}
  labels: {}
  livenessProbe:
    exec:
      command:
        - curl
        - -f
        - http://localhost/health_checks/default
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
  readinessProbe: {}
  resources: {}
  persistentVolumeClaim:
    enabled: true
    annotations: {}
    spec:
      storageClassName: ""
      volumeName: '{{ template "app.name" . }}-opdata'
  service:
    type: ClusterIP
    annotations: {}
    labels: {}


backend:
  image: #if not set here, taken from global variable openproject_image
  networks: 
    - backend
  strategy: Recreate
  env:
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
    RAILS_CACHE_STORE: memcache
    RAILS_MAX_THREADS: "16"
    RAILS_MIN_THREADS: "4"
    OPENPROJECT_EDITION: standard
  annotations: {}
  labels: {}
  cron:
    livenessProbe: {}
    readinessProbe: {}
    resources: {}
    restartPolicy: Always
  worker:
    replicas: 2
    livenessProbe: {}
    readinessProbe: {}
    resources: {}
    restartPolicy: Always
  persistentVolumeClaim:
    enabled: true
    annotations: {}
    spec:
      storageClassName: ""
      volumeName: '{{ template "app.name" . }}-opdata'

persistentVolumes:
  - name: '{{ template "app.name" . }}-database'
    spec:
      claimRef:
        name: '{{ template "app.name" . }}-database'
        namespace: "{{ .Release.Namespace }}"
      # storageClassName: ""
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - name: '{{ template "app.name" . }}-opdata'
    spec:
      claimRef:
        name: '{{ template "app.name" . }}-opdata'
        namespace: "{{ .Release.Namespace }}"
      storageClassName: ""
      capacity:
        storage: 1Mi
      accessModes:
        - ReadWriteMany
      nfs:
        server: nfs-server
        path: "/{{ template \"app.name\" . }}/{{ .Release.Namespace }}"
      mountOptions:
        - nfsvers=4.2

ingress:
  enabled: false
  rules: []
    # - host: example.com
    #   paths:
    #     - path: /subpath
    #     - path: /more

policy:
  networking:
    enabled: true
    networks:
      - frontend
      - backend
